import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Main from "@/components/wrapper/Main";
import { redirect } from "next/navigation";
import Section from "@/components/wrapper/Section";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const loggedIn = false
export default async function publicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //await for the session


  return (
    <>
      <header>{
        <Section style={{
          padding: '1rem 2.5rem'
        }}>
          {loggedIn ? <nav>Logged in  nav</nav> : <nav>Logged out  nav</nav>}
        </Section>
      }</header>
      <Main>{children}</Main>
    </>
  );
}
