import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Main from "@/components/wrapper/Main";
import { redirect } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const loggedIn = false
export default async function publicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //await for the session


  return (
    <>
      <header>{
        loggedIn ? <nav>Logged in  nav</nav> : <nav>Logged out  nav</nav>

      }</header>
      <Main>{children}</Main>
    </>
  );
}
