import type { Metadata } from "next";
import { inter, roboto_mono } from "./fonts";
import "./globals.css";
import Provider from "@/components/Provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto_mono.className}flex flex-col items-center justify-center w-full`}><Provider> {children}</Provider></body>
    </html>
  );
}

//bg-[#EEEBE7]