import type { Metadata } from "next";
import { inter, roboto_mono } from "./fonts";
import "./globals.css";
import Provider from "@/components/Provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="flex w-screen items-center justify-center" lang="en">
    
      <body className={`${roboto_mono.className} max-w-[1400px] w-full bg-app-background flex flex-col items-center justify-center`}><Provider> {children} </Provider></body>
    </html>
  );
}

//bg-[#EEEBE7]