import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Main from "@/components/wrapper/Main";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const isLoggedIn = true


export default async function publicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //await for the session
  const session = await getServerSession(authOptions)
  if (!session) {
    redirect('/')
  }

  return (
    <>
      {children}
    </>
  );
}
